### ISSUE TITLE
[install] Update setup

### ISSUE THREAD

**Issue by atb00ker** [iknite/ansible-spotify#6]
I think the installation procedure needs to be updated, I had to add:

```
- name: Add spotify signing key
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present
```

to make it work, please check the procedure here: https://www.spotify.com/in/download/linux/

**Comment by sybernomad** [comment]
At the time of this writing it looks like the key's changed:

```
---
# spotify
- name: Add spotify signing key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present

- name: Add spotify repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free'
    state: present

- name: Install spotify
  package:
    name:
      - spotify-client
    state: present
  ...
  ```
